### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by MLGgamingpro** [heyOwl/SigmaDelete#2]
there are a few unfortunate issues that prevent me from removing sigma client 😔

**1. It only works on some PC's.**
basically, since in the file it says _"C:\Users\User\AppData\Roaming\.minecraft\Sigma\*Sigma5.jar*"_ if your user isn't named "User," it won't work.
(Edit: you can use _%userprofile%_ to select to currently logged-on user)

**2. It doesn't delete some things.**
it doesn't delete the folder _.minecraft/versions/Sigma5_, it also doesn't delete _.minecraft/sigma5_ or _.minecraft/Sigma_. the folder _.minecraft/sigma5_ also contains _youtube-dl.exe_ 😳

**Comment by MLGgamingpro** [comment]
it also doesn't delete the sigmajelloprelauncher, I found that [this](https://github.com/XatzClient/Sigma-Deleter) does a bit of a better job

**Comment by heyOwl** [comment]
tbh i made this as a joke, also thanks for pointing that out

**Comment by heyOwl** [comment]
should work fine now

**Comment by MLGgamingpro** [comment]
you should close this issue as its solved.
