### ISSUE TITLE
General optimization and removal of the unfunny.

### ISSUE THREAD

**Issue by anonfoxer** [heyOwl/SigmaDelete#4]
These are just some proposed changes because I can't open a pull request. Oh well.

First suggestion:
Removal of the racist comment at the beginning of the file. I would recommend if you ever want to pursue any career in IT that you knock this sort of stuff off.

Change 2nd line to `title SigmaDelete`

Second suggestion:
Instead of deleting specific objects in the Sigma folder, which makes no sense when you're trying to remove malware, it is both more space efficient, and more sensible to delete everything all in one go.

Replace lines 7-17 with the following:
`del /f /s /q "C:\Users\%userprofile%\AppData\Roaming\.minecraft\Sigma\*.*"`

While this does not remove the folder names within (no rmdir), it does delete every single object within Sigma and any subfolders. After this, manually deleting the Sigma folders if desired will remove the directories.

**Comment by heyOwl** [comment]
Thanks for the tips.
